#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mwan3helper[-1]
	add ucitrack mwan3helper
	set ucitrack.@mwan3helper[-1].init=mwan3helper
	commit ucitrack
EOF

rm -f /tmp/luci*

/etc/init.d/mwan3helper stop
/etc/init.d/mwan3helper disable

exit 0
