#!/bin/sh

# Exit immediately if a command exits with a non-zero status.
set -e

PRE_INSTALL_DIR="/etc/pre_install"

# Check if the pre-install directory exists and is a directory
if [ -d "${PRE_INSTALL_DIR}" ]; then
    opkg install /etc/pre_install/mosdns_5.3.3-4_aarch64_cortex-a53.ipk --force-depends --force-reinstall
    opkg install luci-app-mosdns_1.6.11_all.ipk --force-depends --force-reinstall
    opkg install luci-i18n-mosdns-zh-cn_git-25.139.47906-df24b19_all.ipk --force-depends --force-reinstall
    
    opkg install cloudflared_2025.4.2-1_aarch64_cortex-a53.ipk --force-depends --force-reinstall
    opkg install luci-app-cloudflared_1.2_all.ipk --force-depends --force-reinstall
    opkg install luci-i18n-cloudflared-zh-cn_git-25.140.42380-0d92cc6_all.ipk --force-depends --force-reinstall
fi

/etc/pre_install

exit 0
